### ISSUE TITLE
Update for the Dojo 1.11.1 release

### ISSUE THREAD

**Issue by k-wall** [cometd/dojo-maven#3]
Hello,

Would you be able to make available maven artefacts for the new Dojo 1.11.1 release?

Thanks in advance, I appreciate the effort.

**Comment by gregw** [comment]
@sbordet Hmm I tried to release but oss failed to close saying: `com.sonatype.nexus.staging.StagingConfigurationException: org.sonatype.nexus.proxy.NoSuchRepositoryException: Repository with ID="dojo-with-staging" not found`

any idea what is going on there?  

The open stage is in dojo-1009

**Comment by sbordet** [comment]
Dropped `dojo-1009`, updated the poms, retried myself, but got the same error.

Filed https://issues.sonatype.org/browse/OSSRH-21886, let's see what they say.

**Comment by sbordet** [comment]
Was a OSSRH problem that they fixed.

This repository will be updated just after the upcoming CometD 3.0.10 release.

**Comment by k-wall** [comment]
Thanks to all involved.
