### ISSUE TITLE
Maven artefacts for Dojo 1.11.1 release omits the new flat theme

### ISSUE THREAD

**Issue by k-wall** [cometd/dojo-maven#4]
Hi all,

I notice that the new maven artefacts produced for Dojo 1.11.1 are missing the 'flat' theme that is present in the distribution http://download.dojotoolkit.org/release-1.11.1/dojo-release-1.11.1.zip.  

I am referring to directory:

dojo-release-1.11.1/themes/flat/

Is there a reason why this is so? Why is the maven artefact simply not the artefact produced by dojotoolkit.org?

We are very  keen to use the flat theme so it would be appreciated if this could be corrected.

Thanks for maintaining these artefacts.

Keith.

**Comment by sbordet** [comment]
I just downloaded the `dojo-war-1.11.1.war` from Maven Central and it **does** contain the `themes/flat` directory.

**Comment by k-wall** [comment]
The files are missing from dojo-1.11.1-distribution.zip.

**Comment by sbordet** [comment]
I don't understand ? They are present in `dojo-1.11.1-distribution.zip`, and we just repackage the distribution into a `war` format, so it all looks good to me.

**Comment by k-wall** [comment]
I don't see them.  Comparing the artefact from Maven central with the one from Dojo:

Maven:
unzip -l ~/.m2/repository/org/dojotoolkit/dojo/1.11.1/dojo-1.11.1-distribution.zip | grep flat
(nothing)

curl -O http://download.dojotoolkit.org/release-1.11.1/dojo-release-1.11.1.zip
unzip -l  dojo-release-1.11.1.zip  | grep flat
        0  03-29-16 23:59   dojo-release-1.11.1/themes/flat/
     2823  03-29-16 23:59   dojo-release-1.11.1/themes/flat/flat_dijit_rtl.css
     6922  03-29-16 23:59   dojo-release-1.11.1/themes/flat/flat_rtl.css
    34074  03-29-16 23:59   dojo-release-1.11.1/themes/flat/flat_dijit.css
        0  03-29-16 23:59   dojo-release-1.11.1/themes/flat/dijit/
        0  03-29-16 23:59   dojo-release-1.11.1/themes/flat/dijit/Editor_rtl.css
      157  03-29-16 23:59   dojo-release-1.11.1/themes/flat/dijit/TitlePane_rtl.css

What I am doing wrong?

**Comment by sbordet** [comment]
You're doing nothing wrong, the module is repackaging the distribution from Dojo in the wrong way.

**Comment by sbordet** [comment]
Thanks !

**Comment by k-wall** [comment]
Thanks for addressing the underlying problem.  One question, will artefacts for 1.11.1 at maven central be corrected or will this need to await the next release?

**Comment by sbordet** [comment]
It's scheduled for the next Dojo release, unless you really need this.
What would be a good numbering scheme here ? 1.11.1.1 ?

**Comment by k-wall** [comment]
We will await the next Dojo maintenance release.  Thanks again.

**Comment by sbordet** [comment]
Released 1.11.2.
